"""Pipeline utilities: feature extraction, selectors, builders, metrics, data utils."""

from .feature_engine import (
    EmbeddingComputer,
    FeatureEngine,
    InterpretableFeatureExtractor,
)
from .selectors import CumulativeFeatureSelector
from .logger import PipelineLogger
from .metrics import (
    display_full_metrics,
    plot_evaluation_results,
    plot_train_test_curves,
    plot_confusion_matrix_custom,
    plot_feature_importance,
    save_roc_pr_curves,
    plot_roc_pr_curves,
    save_feature_importance_hybrid,
    plot_hybrid_feature_importance,
    plot_correlation_heatmap,
    plot_embedding_projection,
    plot_learning_curve_sklearn,
    plot_feature_importance_for_paper,
    print_paper_style_results,
    save_feature_importance_table,
)
from .data_utils import (
    load_data,
    create_feature_matrix,
    get_cache_filename,
    save_feature_matrix_h5,
    load_feature_matrix_h5,
    split_pairs_no_overlap,
    make_protein_folds,
    build_esm_only_pair_matrix,
    get_protein_based_splits,
    get_cluster_based_splits,
    load_cluster_map,
)
from .builders import (
    create_lgbm_pipeline,
    create_stacking_pipeline,
    create_svm_pipeline,
    create_embed_only_pipeline,
    create_interp_only_pipeline,
    create_esm_lr_pipeline,
    create_esm_lgbm_raw_pipeline,
    create_esm_lgbm_selector_pipeline,
)

__all__ = [
    "EmbeddingComputer",
    "FeatureEngine",
    "InterpretableFeatureExtractor",
    "CumulativeFeatureSelector",
    "PipelineLogger",
    "display_full_metrics",
    "plot_evaluation_results",
    "plot_train_test_curves",
    "plot_confusion_matrix_custom",
    "plot_feature_importance",
    "save_roc_pr_curves",
    "plot_roc_pr_curves",
    "save_feature_importance_hybrid",
    "plot_hybrid_feature_importance",
    "plot_correlation_heatmap",
    "plot_embedding_projection",
    "plot_learning_curve_sklearn",
    "plot_feature_importance_for_paper",
    "print_paper_style_results",
    "save_feature_importance_table",
    "load_data",
    "create_feature_matrix",
    "get_cache_filename",
    "save_feature_matrix_h5",
    "load_feature_matrix_h5",
    "split_pairs_no_overlap",
    "make_protein_folds",
    "build_esm_only_pair_matrix",
    "get_protein_based_splits",
    "get_cluster_based_splits",
    "load_cluster_map",
    "create_lgbm_pipeline",
    "create_stacking_pipeline",
    "create_svm_pipeline",
    "create_embed_only_pipeline",
    "create_interp_only_pipeline",
    "create_esm_lr_pipeline",
    "create_esm_lgbm_raw_pipeline",
    "create_esm_lgbm_selector_pipeline",
]
